import { randomBytes } from 'crypto';
import { Injectable } from '@nestjs/common';

@Injectable()
export class Base62Generator {
  private readonly chars =
    '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';

  // Generates randomized 6 characters shortcode
  generate(length: number = 6): string {
    let result = '';
    const bytes = randomBytes(length);
    for (let i = 0; i < length; i++) {
      // Map byte value to our 62 characters (ensures generated byte maps to valid character in char string)
      result += this.chars[bytes[i] % 62];
    }
    return result;
  }
}
